---
# Copyright (C) 2023 Robert Wimmer
# SPDX-License-Identifier: GPL-3.0-or-later

dependency:
  name: galaxy

driver:
  name: vagrant
  provider:
    name: libvirt
    type: libvirt

platforms:
  - name: test-longhorn-assets
    box: generic/ubuntu2004
    memory: 1024
    cpus: 2
    groups:
      - vpn
      - k8s_assets
      - k8s
    interfaces:
      - auto_config: true
        network_name: private_network
        type: static
        ip: 192.168.10.5
  - name: test-longhorn-controller1
    box: generic/ubuntu2004
    memory: 2048
    cpus: 2
    groups:
      - vpn
      - k8s_controller
      - k8s_worker
      - k8s_etcd
      - k8s
    interfaces:
      - auto_config: true
        network_name: private_network
        type: static
        ip: 192.168.10.10
  - name: test-longhorn-controller2
    box: generic/ubuntu2004
    memory: 2048
    cpus: 2
    groups:
      - vpn
      - k8s_controller
      - k8s_worker
      - k8s_etcd
      - k8s
    interfaces:
      - auto_config: true
        network_name: private_network
        type: static
        ip: 192.168.10.20
  - name: test-longhorn-controller3
    box: generic/ubuntu2004
    memory: 2048
    cpus: 2
    groups:
      - vpn
      - k8s_controller
      - k8s_worker
      - k8s_etcd
      - k8s
    interfaces:
      - auto_config: true
        network_name: private_network
        type: static
        ip: 192.168.10.30
  - name: test-longhorn-worker1
    box: generic/ubuntu2004
    memory: 2048
    cpus: 2
    provider_raw_config_args:
      - "storage :file, :type => 'qcow2', :device => 'vdb', :size => '1G'"
    groups:
      - vpn
      - lvm
      - k8s_worker
      - k8s_longhorn_system
      - k8s_longhorn_user
      - k8s
    interfaces:
      - auto_config: true
        network_name: private_network
        type: static
        ip: 192.168.10.100
  - name: test-longhorn-worker2
    box: generic/ubuntu2004
    memory: 2048
    cpus: 2
    provider_raw_config_args:
      - "storage :file, :type => 'qcow2', :device => 'vdb', :size => '1G'"
    groups:
      - vpn
      - lvm
      - k8s_worker
      - k8s_longhorn_user
      - k8s
    interfaces:
      - auto_config: true
        network_name: private_network
        type: static
        ip: 192.168.10.110
  - name: test-longhorn-worker3
    box: generic/ubuntu2004
    memory: 2048
    cpus: 2
    provider_raw_config_args:
      - "storage :file, :type => 'qcow2', :device => 'vdb', :size => '1G'"
    groups:
      - vpn
      - lvm
      - k8s_worker
      - k8s_longhorn_user
      - k8s_longhorn_system
      - k8s
    interfaces:
      - auto_config: true
        network_name: private_network
        type: static
        ip: 192.168.10.120
  - name: test-longhorn-worker4
    box: generic/ubuntu2004
    memory: 2048
    cpus: 2
    provider_raw_config_args:
      - "storage :file, :type => 'qcow2', :device => 'vdb', :size => '1G'"
    groups:
      - vpn
      - lvm
      - k8s_worker
      - k8s_longhorn_system
      - k8s
    interfaces:
      - auto_config: true
        network_name: private_network
        type: static
        ip: 192.168.10.130

provisioner:
  name: ansible
  connection_options:
    ansible_ssh_user: vagrant
    ansible_become: true
  log: true
  lint: yamllint . && flake8 && ansible-lint

scenario:
  name: default
  test_sequence:
    - prepare
    - converge

verifier:
  name: ansible
  enabled: true
