---
# Copyright (C) 2023 Robert Wimmer
# SPDX-License-Identifier: GPL-3.0-or-later

- name: Update cache
  hosts: k8s, k8s_etcd
  remote_user: vagrant
  become: true
  gather_facts: true
  tasks:
    - name: Update APT package cache
      ansible.builtin.apt:
        update_cache: true
        upgrade: true
        cache_valid_time: 3600

- name: Reboot hosts if required
  hosts: k8s, k8s_etcd
  remote_user: vagrant
  become: true
  tasks:
    - name: Check if reboot is required because of kernel update
      ansible.builtin.stat:
        path: /var/run/reboot-required
      register: reboot_required_kernel_check

    - name: Collect reboot information
      ansible.builtin.set_fact:
        reboot_required_kernel: "{{ reboot_required_kernel_check.stat.exists }}"

    - name: Check if reboot is required because of package update
      ansible.builtin.stat:
        path: /var/run/reboot-required.pkgs
      register: reboot_required_pkgs_check

    - name: Collect reboot information
      ansible.builtin.set_fact:
        reboot_required_pkgs: "{{ reboot_required_pkgs_check.stat.exists }}"

    - name: Reboot for kernel updates
      when: |
        reboot_required_kernel or
        reboot_required_pkgs
      ansible.builtin.reboot:

- name: Ignore PEP 668 because it is silly
  hosts: k8s_assets
  remote_user: vagrant
  become: true
  tasks:
    - name: Remove /usr/lib/python3.12/EXTERNALLY-MANAGED
      ansible.builtin.file:
        path: "/usr/lib/python3.12/EXTERNALLY-MANAGED"
        state: absent

- name: Setup Kubernetes client tooling
  hosts: k8s_assets
  become: true
  gather_facts: true
  tasks:
    - name: Install kubectl
      ansible.builtin.include_role:
        name: githubixx.kubectl

    - name: Install support packages
      ansible.builtin.package:
        name: "{{ packages }}"
        state: present
      vars: 
        packages:
          - conntrack
          - python3-pip

    - name: Install kubernetes Python package
      ansible.builtin.pip:
        name: kubernetes
        state: present

    - name: Install Helm role
      ansible.builtin.include_role:
        name: gantsign.helm

- name: Harden hosts
  hosts: all
  remote_user: vagrant
  become: true
  gather_facts: true
  tasks:
    - name: Setup harden_linux role
      ansible.builtin.include_role:
        name: githubixx.harden_linux

- name: Setup Wireguard VPN
  hosts: vpn
  remote_user: vagrant
  become: true
  gather_facts: true
  tasks:
    - name: Setup wireguard role
      ansible.builtin.include_role:
        name: githubixx.ansible_role_wireguard

- name: Setup cfssl
  hosts: k8s_assets
  become: true
  gather_facts: false
  tasks:
    - name: Install cfssl
      ansible.builtin.include_role:
        name: githubixx.cfssl

- name: Setup Kubernetes certificates
  hosts: k8s_assets
  gather_facts: false
  tasks:
    - name: Generate etcd and K8s TLS certificates
      ansible.builtin.include_role:
        name: githubixx.kubernetes_ca

    - name: Copy certificate files from assets to local host
      ansible.posix.synchronize:
        mode: pull
        src: "{{ k8s_ca_conf_directory }}"
        dest: "/tmp"

- name: Setup etcd
  hosts: k8s_etcd
  remote_user: vagrant
  become: true
  gather_facts: true
  tasks:
    - name: Include etcd role
      ansible.builtin.include_role:
        name: githubixx.etcd

- name: Setup Kubernetes client tooling
  hosts: k8s_assets
  become: true
  gather_facts: true
  tasks:
    - name: Install kubectl
      ansible.builtin.include_role:
        name: githubixx.kubectl

    - name: Install support packages
      ansible.builtin.package:
        name: "{{ packages }}"
        state: present
      vars:
        packages:
          - conntrack
          - python3-kubernetes

    - name: Install Helm role
      ansible.builtin.include_role:
        name: gantsign.helm

- name: Setup HAProxy
  hosts: haproxy
  remote_user: vagrant
  become: true
  gather_facts: true
  tasks:
    - name: Setup haproxy role
      ansible.builtin.include_role:
        name: githubixx.haproxy

- name: Setup containerd
  hosts: k8s_worker
  become: true
  gather_facts: true
  tasks:
    - name: Include runc role
      ansible.builtin.include_role:
        name: githubixx.runc

    - name: Include CNI role
      ansible.builtin.include_role:
        name: githubixx.cni

    - name: Include containerd role
      ansible.builtin.include_role:
        name: githubixx.containerd

- name: Setup Kubernetes controller
  hosts: k8s_controller
  become: true
  gather_facts: true
  tasks:
    - name: Include kubernetes_controller role
      ansible.builtin.include_role:
        name: githubixx.kubernetes_controller

- name: Prepare kubeconfig for vagrant user
  hosts: k8s_assets
  become: true
  gather_facts: false
  vars:
    k8s_controller__vagrant_kube_directory: "/home/vagrant/.kube"
  tasks:
    - name: Ensure .kube directory in vagrant home
      ansible.builtin.file:
        path: "{{ k8s_controller__vagrant_kube_directory }}"
        state: directory
        mode: "0700"
        owner: "vagrant"
        group: "vagrant"

    - name: Copy admin.kubeconfig to vagrant home directory
      ansible.builtin.copy:
        src: "{{ k8s_admin_conf_dir }}/admin.kubeconfig"
        dest: "{{ k8s_controller__vagrant_kube_directory }}/config"
        mode: "0400"
        remote_src: true
        owner: "vagrant"
        group: "vagrant"

- name: Setup LVM volumes for Longhorn
  hosts: lvm
  become: true
  gather_facts: true
  tasks:
    - name: Include LVM role
      ansible.builtin.include_role:
        name: githubixx.lvm

- name: Setup Kubernetes worker
  hosts: k8s_worker
  become: true
  gather_facts: true
  tasks:
    - name: Include kubernetes_worker role
      ansible.builtin.include_role:
        name: githubixx.kubernetes_worker

- name: Setup Cilium CLI
  hosts: test-assets
  become: true
  tasks:
    - name: Include cilium_cli role
      ansible.builtin.include_role:
        name: githubixx.cilium_cli

- name: Gather facts
  hosts: all
  become: true
  gather_facts: true
  tasks:
    - name: Populate Ansible hostVars
      ansible.builtin.setup:

- name: Setup Cilium
  hosts: k8s_worker
  become: true
  environment:
    K8S_AUTH_KUBECONFIG: "{{ k8s_admin_conf_dir }}/admin.kubeconfig"
  tasks:
    - name: Include Cilium role
      ansible.builtin.include_role:
        name: githubixx.cilium_kubernetes
      vars:
        cilium_action: "install"  # noqa var-naming

- name: Setup tooling to make worker nodes usable
  hosts: test-assets
  become: true
  gather_facts: true
  environment:
    K8S_AUTH_KUBECONFIG: "{{ k8s_admin_conf_dir }}/admin.kubeconfig"
  tasks:
    - name: Waiting for Cilium to become ready
      ansible.builtin.include_tasks:
        file: tasks/cilium_status.yml

    - name: Control plane nodes should only run Cilium pods
      ansible.builtin.include_tasks:
        file: tasks/taint_controller_nodes.yml

    - name: Install CoreDNS
      ansible.builtin.include_tasks:
        file: tasks/coredns.yml

    - name: Waiting for CoreDNS to become ready
      ansible.builtin.include_tasks:
        file: tasks/coredns_status.yml
