---
# Copyright (C) 2023 Robert Wimmer
# SPDX-License-Identifier: GPL-3.0-or-later

- name: Update cache
  hosts: k8s
  gather_facts: true
  tasks:
    - name: Update APT package cache
      ansible.builtin.apt:
        update_cache: true
        cache_valid_time: 3600

- name: Harden hosts
  hosts: all
  gather_facts: true
  tasks:
    - name: Setup harden_linux role
      ansible.builtin.include_role:
        name: githubixx.harden_linux

- name: Setup Wireguard VPN
  hosts: vpn
  gather_facts: true
  tasks:
    - name: Setup wireguard role
      ansible.builtin.include_role:
        name: githubixx.ansible_role_wireguard

- name: Setup cfssl
  hosts: k8s_assets
  gather_facts: false
  tasks:
    - name: Install cfssl
      ansible.builtin.include_role:
        name: githubixx.cfssl

- name: Setup Kubernetes certificates
  hosts: k8s_assets
  gather_facts: false
  tasks:
    - name: Generate etcd and K8s TLS certificates
      ansible.builtin.include_role:
        name: githubixx.kubernetes_ca

    - name: Copy certificate files from assets to local host
      ansible.posix.synchronize:
        mode: pull
        src: "{{ k8s_ca_conf_directory }}"
        dest: "/tmp"

- name: Setup etcd
  hosts: k8s_etcd
  gather_facts: true
  tasks:
    - name: Include etcd role
      ansible.builtin.include_role:
        name: githubixx.etcd

- name: Setup Kubernetes client tooling
  hosts: k8s_assets
  gather_facts: true
  tasks:
    - name: Install kubectl
      ansible.builtin.include_role:
        name: githubixx.kubectl

    - name: Install support packages
      ansible.builtin.package:
        name: "{{ packages }}"
        state: present
      vars:
        packages:
          - conntrack
          - python3-pip

    - name: Install kubernetes Python package
      ansible.builtin.pip:
        name: kubernetes
        state: present

    - name: Install Helm role
      ansible.builtin.include_role:
        name: gantsign.helm

- name: Setup HAProxy
  hosts: ubuntu22
  gather_facts: true
  tasks:
    - name: Setup haproxy role
      ansible.builtin.include_role:
        name: githubixx.haproxy

- name: Install runc, CNI plugins and containerd
  hosts: k8s_worker
  gather_facts: true
  tasks:
    - name: Include runc role
      ansible.builtin.include_role:
        name: githubixx.runc

    - name: Include CNI role
      ansible.builtin.include_role:
        name: githubixx.cni

    - name: Include containerd role
      ansible.builtin.include_role:
        name: githubixx.containerd

- name: Setup Kubernetes controller
  hosts: k8s_controller
  gather_facts: true
  tasks:
    - name: Include kubernetes_controller role
      ansible.builtin.include_role:
        name: githubixx.kubernetes_controller

- name: Prepare kubeconfig for vagrant user
  hosts: k8s_assets
  gather_facts: false
  vars:
    k8s_controller__vagrant_kube_directory: "/home/vagrant/.kube"
  tasks:
    - name: Ensure .kube directory in vagrant home
      ansible.builtin.file:
        src: "{{ k8s_admin_conf_dir }}/admin.kubeconfig"
        dest: "{{ k8s_admin_conf_dir }}/config"
        state: link
        owner: "vagrant"
        group: "vagrant"

- name: Setup LVM volumes for Longhorn
  hosts: lvm
  gather_facts: true
  tasks:
    - name: Include LVM role
      ansible.builtin.include_role:
        name: githubixx.lvm

- name: Setup K8s worker
  hosts: k8s_worker
  gather_facts: true
  tasks:
    - name: Setup Kubernetes worker
      ansible.builtin.include_role:
        name: githubixx.kubernetes_worker

- name: Setup Cilium
  hosts: k8s_worker
  gather_facts: true
  environment:
    K8S_AUTH_KUBECONFIG: "{{ k8s_admin_conf_dir }}/admin.kubeconfig"
  tasks:
    - name: Include Cilium role
      ansible.builtin.include_role:
        name: githubixx.cilium_kubernetes
      vars:
        cilium_action: "install"  # noqa var-naming

- name: Setup tooling to make worker nodes usable
  hosts: test-assets
  become: true
  gather_facts: true
  environment:
    K8S_AUTH_KUBECONFIG: "{{ k8s_admin_conf_dir }}/admin.kubeconfig"
  tasks:
    - name: Setup tooling
      block:
        - name: Waiting for Cilium to become ready
          ansible.builtin.include_tasks:
            file: tasks/cilium_status.yml

        - name: Control plane nodes should only run Cilium pods
          ansible.builtin.include_tasks:
            file: tasks/taint_controller_nodes.yml

        - name: Install CoreDNS
          ansible.builtin.include_tasks:
            file: tasks/coredns.yml

        - name: Waiting for CoreDNS to become ready
          ansible.builtin.include_tasks:
            file: tasks/coredns_status.yml
