---
# Copyright (C) 2023 Robert Wimmer
# SPDX-License-Identifier: GPL-3.0-or-later

- name: Verify setup
  hosts: test-assets
  environment:
    K8S_AUTH_KUBECONFIG: "{{ k8s_admin_conf_dir }}/admin.kubeconfig"
  tasks:
    - name: Fetch longhorn-manager DaemonSet information
      kubernetes.core.k8s_info:
        api_version: v1
        kind: DaemonSet
        name: longhorn-manager
        namespace: longhorn-system
      register: longhorn_verify_longhorn_manager_daemonset_info

    - name: Print DaemonSet JSON blob
      ansible.builtin.debug:
        var: longhorn_verify_longhorn_manager_daemonset_info
      when: ansible_verbosity > 1
      
    - name: There should be a DaemonSet called longhorn-manager
      ansible.builtin.assert:
        that:
          - longhorn_verify_longhorn_manager_daemonset_info.resources[0].metadata.name == "longhorn-manager"
          
    - name: There should be at least one Longhorn pod running
      ansible.builtin.assert: 
        that:
          - (longhorn_verify_longhorn_manager_daemonset_info.resources[0].status.numberReady | default(0) | int) >= 1
